### ISSUE TITLE
Support for LifX

### ISSUE THREAD

**Issue by Inza** [mitchellallison/WarningLights#6]
Hello Mitchell,

do you plan to add support for LifX too?

**Comment by mitchellallison** [comment]
Hey,

There are currently no plans for WarningLights to support LIFX. This is mainly due to time constraints, but also because I don't have any bulbs to test with. For this reason, I'd be hesitant to accept any pull requests as it's difficult for me to judge the PRs correctness.

However, the code is open-sourced under the MIT license. Given the presence of a good LIFX SDK, porting to LIFX shouldn't be too much work. I'd encourage you to create a fork of the project, add support and submit the plug-in to Alcatraz if it's something you're interested in!

Thanks!
